---
# Application settings
app_name: task_manager
app_user: deploy
app_group: deploy
app_dir: /home/deploy/task_manager
repo_url: https://github.com/EdvardLaub/task-manager.git  # Update this
repo_branch: main

# Python settings
python_version: "3.10"
venv_path: "{{ app_dir }}/venv"

# Database settings
db_name: task_manager_db
db_user: task_manager_user

# Nginx settings
nginx_server_name: 167.71.32.251  # Update this
nginx_client_max_body_size: 10M

# SSL settings (set to false for now)
ssl_enabled: false

# Django settings
django_settings_module: taskmanager.production_settings
allowed_hosts: 
  - YOUR_DROPLET_IP  # Update this
  - localhost
  - 127.0.0.1

# Gunicorn settings
gunicorn_workers: 3
gunicorn_bind: 127.0.0.1:8000
