- name: Start and enable PostgreSQL
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    state: present
  become_user: postgres

- name: Create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    db: "{{ db_name }}"
    priv: ALL
    state: present
  become_user: postgres

- name: Initialize database tables
  shell: |
    source {{ venv_dir }}/bin/activate
    cd {{ app_dir }}
    python manage.py
  become_user: "{{ app_user }}"
  environment:
    DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password }}@localhost/{{ db_name }}"
    FLASK_ENV: "production"
  ignore_errors: yes
EOF