---
- name: Create Supervisor configuration
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/{{ app_name }}.conf
    backup: yes
  notify: restart supervisor

- name: Start and enable Supervisor
  systemd:
    name: supervisor
    state: started
    enabled: yes

- name: Reread Supervisor configuration
  supervisorctl:
    name: "{{ app_name }}"
    state: restarted
